//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomatedTests.CMP.Inventory {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Inven : global::System.Configuration.ApplicationSettingsBase {
        
        private static Inven defaultInstance = ((Inven)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Inven())));
        
        public static Inven Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//input[@value=\'Submit\']")]
        public string QSubmitB {
            get {
                return ((string)(this["QSubmitB"]));
            }
            set {
                this["QSubmitB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//input[@value=\"New\"]")]
        public string NewB {
            get {
                return ((string)(this["NewB"]));
            }
            set {
                this["NewB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//input[@value=\"Save\"]")]
        public string SaveB {
            get {
                return ((string)(this["SaveB"]));
            }
            set {
                this["SaveB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//input[@value=\"Delete\"]")]
        public string DeleteB {
            get {
                return ((string)(this["DeleteB"]));
            }
            set {
                this["DeleteB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//input[@value=\"OK\"]")]
        public string OKB {
            get {
                return ((string)(this["OKB"]));
            }
            set {
                this["OKB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//input[@value=\"Remove\"]")]
        public string RemoveB {
            get {
                return ((string)(this["RemoveB"]));
            }
            set {
                this["RemoveB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//input[@value=\"Add\"]")]
        public string AddB {
            get {
                return ((string)(this["AddB"]));
            }
            set {
                this["AddB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//input[@value=\"Edit\"]")]
        public string EditB {
            get {
                return ((string)(this["EditB"]));
            }
            set {
                this["EditB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//input[@value=\"Add Non Contracted\"]")]
        public string AddContractB {
            get {
                return ((string)(this["AddContractB"]));
            }
            set {
                this["AddContractB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//input[@value=\"Modify\"]")]
        public string ModifyB {
            get {
                return ((string)(this["ModifyB"]));
            }
            set {
                this["ModifyB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//input[@value=\"Expire\"]")]
        public string ExpireB {
            get {
                return ((string)(this["ExpireB"]));
            }
            set {
                this["ExpireB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//input[@value=\"Reset\"]")]
        public string ResetB {
            get {
                return ((string)(this["ResetB"]));
            }
            set {
                this["ResetB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//input[@value=\"Accept\"]")]
        public string AcceptB {
            get {
                return ((string)(this["AcceptB"]));
            }
            set {
                this["AcceptB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//input[@value=\"Done\"]")]
        public string DoneB {
            get {
                return ((string)(this["DoneB"]));
            }
            set {
                this["DoneB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//input[@value=\"Close\"]")]
        public string CloseB {
            get {
                return ((string)(this["CloseB"]));
            }
            set {
                this["CloseB"] = value;
            }
        }
    }
}
