//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomatedTests.CMP.Admin {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class General : global::System.Configuration.ApplicationSettingsBase {
        
        private static General defaultInstance = ((General)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new General())));
        
        public static General Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//input[@value=\'New\']")]
        public string NewB {
            get {
                return ((string)(this["NewB"]));
            }
            set {
                this["NewB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//input[@value=\'Save\']")]
        public string SaveB {
            get {
                return ((string)(this["SaveB"]));
            }
            set {
                this["SaveB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//input[@value=\'Remove\']")]
        public string RemoveB {
            get {
                return ((string)(this["RemoveB"]));
            }
            set {
                this["RemoveB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//input[@value=\'Submit\']")]
        public string SubmitB {
            get {
                return ((string)(this["SubmitB"]));
            }
            set {
                this["SubmitB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//input[@value=\'Delete\']")]
        public string DeleteB {
            get {
                return ((string)(this["DeleteB"]));
            }
            set {
                this["DeleteB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//input[@value=\'Copy\']")]
        public string CopyB {
            get {
                return ((string)(this["CopyB"]));
            }
            set {
                this["CopyB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//input[@value=\'Close\']")]
        public string CloseB {
            get {
                return ((string)(this["CloseB"]));
            }
            set {
                this["CloseB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//input[@value=\'Add\']")]
        public string AddB {
            get {
                return ((string)(this["AddB"]));
            }
            set {
                this["AddB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//input[@value=\'OK\']")]
        public string OKB {
            get {
                return ((string)(this["OKB"]));
            }
            set {
                this["OKB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//input[@value=\'Create\']")]
        public string CreateB {
            get {
                return ((string)(this["CreateB"]));
            }
            set {
                this["CreateB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//input[@value=\'Reset\']")]
        public string ResetB {
            get {
                return ((string)(this["ResetB"]));
            }
            set {
                this["ResetB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//input[@value=\'Add Rate\']")]
        public string AddRateB {
            get {
                return ((string)(this["AddRateB"]));
            }
            set {
                this["AddRateB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//input[@value=\'Update\']")]
        public string UpdateB {
            get {
                return ((string)(this["UpdateB"]));
            }
            set {
                this["UpdateB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//input[@value=\'Cancel\']")]
        public string CancelB {
            get {
                return ((string)(this["CancelB"]));
            }
            set {
                this["CancelB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//input[@value=\'Restore\']")]
        public string RestoreB {
            get {
                return ((string)(this["RestoreB"]));
            }
            set {
                this["RestoreB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//input[@value=\'Details\']")]
        public string DetailsB {
            get {
                return ((string)(this["DetailsB"]));
            }
            set {
                this["DetailsB"] = value;
            }
        }
    }
}
