//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomatedTests.CMP.Contracts {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Contra : global::System.Configuration.ApplicationSettingsBase {
        
        private static Contra defaultInstance = ((Contra)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Contra())));
        
        public static Contra Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//input[@value=\'Submit\']")]
        public string QuerySubmitB {
            get {
                return ((string)(this["QuerySubmitB"]));
            }
            set {
                this["QuerySubmitB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//input[@value=\'New\']")]
        public string CreateNewB {
            get {
                return ((string)(this["CreateNewB"]));
            }
            set {
                this["CreateNewB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//input[@value=\'Save\']")]
        public string SaveB {
            get {
                return ((string)(this["SaveB"]));
            }
            set {
                this["SaveB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//input[@value=\"OK\"]")]
        public string OKB {
            get {
                return ((string)(this["OKB"]));
            }
            set {
                this["OKB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//input[@value=\"Copy\"]")]
        public string CopyB {
            get {
                return ((string)(this["CopyB"]));
            }
            set {
                this["CopyB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//input[@value=\"Delete\"]")]
        public string DeleteB {
            get {
                return ((string)(this["DeleteB"]));
            }
            set {
                this["DeleteB"] = value;
            }
        }
    }
}
