//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AutomatedTests.CMP.Enterprise {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Enterp : global::System.Configuration.ApplicationSettingsBase {
        
        private static Enterp defaultInstance = ((Enterp)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Enterp())));
        
        public static Enterp Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//input[@value=\'Submit\']")]
        public string QuerySubmitB {
            get {
                return ((string)(this["QuerySubmitB"]));
            }
            set {
                this["QuerySubmitB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//input[@value=\'New\']")]
        public string CreateNewB {
            get {
                return ((string)(this["CreateNewB"]));
            }
            set {
                this["CreateNewB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//input[@value=\'Save\']")]
        public string SaveB {
            get {
                return ((string)(this["SaveB"]));
            }
            set {
                this["SaveB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//input[@value=\'Add\']")]
        public string AddB {
            get {
                return ((string)(this["AddB"]));
            }
            set {
                this["AddB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//input[@value=\'OK\']")]
        public string OKB {
            get {
                return ((string)(this["OKB"]));
            }
            set {
                this["OKB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//input[@value=\'Delete\']")]
        public string DeleteB {
            get {
                return ((string)(this["DeleteB"]));
            }
            set {
                this["DeleteB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//input[@value=\'Create\']")]
        public string CreateB {
            get {
                return ((string)(this["CreateB"]));
            }
            set {
                this["CreateB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//input[@value=\'Modify\']")]
        public string ModifyB {
            get {
                return ((string)(this["ModifyB"]));
            }
            set {
                this["ModifyB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//input[@value=\'Reset\']")]
        public string ResetB {
            get {
                return ((string)(this["ResetB"]));
            }
            set {
                this["ResetB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//input[@value=\'false\']")]
        public string CheckB {
            get {
                return ((string)(this["CheckB"]));
            }
            set {
                this["CheckB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//input[@value=\'Expire\']")]
        public string ExpireB {
            get {
                return ((string)(this["ExpireB"]));
            }
            set {
                this["ExpireB"] = value;
            }
        }
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("//input[@value=\'Update\']")]
        public string UpdateB {
            get {
                return ((string)(this["UpdateB"]));
            }
            set
            {
                this["UpdateB"] = value;
            }
        }

            }

    }

